# Maximilian Jaramazovic
#* This Docker compose file is responsible to create the necessary infrastructure for the gains app.
#* In order to develop and test use in cli: docker compose up
#* When you are done: docker compose down
#*
#! when connecting pgadmin use the container name, not address
#! in production best practice would be to change uname and pass and have them hidden too :D
# Maximilian Jaramazovic

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
    #* postgres container
    database:
        image: postgres:18
        container_name: hunter_poster-postgres
        env_file:
            - ./.env
        command:
            [
                "postgres",
                "-c",
                "log_statement=all",
                "-c",
                "log_parameter_max_length=0",
                "-c",
                "log_parameter_max_length_on_error=0",
            ]
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql #persistent data
            - ./src/database/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro #postgres schema
            - ./src/database/seed.sql:/docker-entrypoint-initdb.d/002_seed.sql:ro #postgres seed data
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "$DATABASE_URL"]
            interval: 5s
            timeout: 5s
            retries: 5

    #* server container
    # server:
    #     container_name: Hunter-Poster_server
    #     restart: unless-stopped
    #     environment:
    #         DATABASE_URL: ${DATABASE_URL}
    #         JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    #     networks:
    #         - gainz_net

volumes:
    postgres_data:
        driver: local
    pgadmin-data:
